### add models
POST http://localhost:7080/models/add HTTP/1.1
Content-Type: application/json

{
    "name": "test",
    "provider": "test",
    "model_id": "llama2",
    "base_url": "http://localhost:8000",
    "api_key": "test",
    "api_type": "openai"
}

@TXT=帮我写一个关于春天的故事，100字左右即可
### chat
GET http://localhost:7080/chat?txt={{TXT}} HTTP/1.1

